wandb_version: 1

epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 9
learning_rate:
  desc: null
  value: 2.0
experiment_type:
  desc: null
  value: dense
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716225474
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.0
      6: 4.41.0
      8:
      - 5
      13: linux-x86_64
